### ISSUE TITLE
When capturing via Email, only the title is captured, but the body doesn't appear in a child block

### ISSUE THREAD

**Issue by glicksman** [phonetonote/phonetonote-logseq#10]
When capturing via Email, the behaviour is different between Roam vs Logseq.

In Roam:
1. The email is captured, by forwarding to `hello@inbound.phonetonote.com`
2. As a parent block, we get the title of the email
3. As a child block, we get the body of the email

In Logseq:
1. The email is captured, by forwarding to `hello@inbound.phonetonote.com`
2. As a parent block, we get the title of the email
3. **No child block**

This doesn't seem like the intended behavior (when looking at the [code](https://github.com/phonetonote/phonetonote-logseq/commit/979ff75e2fa31460fb1b4c8614b04cf0eea4f03f), is seems like there's a part that is supposed to add children blocks (line 107-108).

**Comment by scottrblock** [comment]
hey @glicksman can you confirm you're on version 0.2.3 of the phonetonote logseq client plugin?

**Comment by e9man** [comment]
Yep:
![image](https://user-images.githubusercontent.com/65280305/162136593-7da4a6e7-ae8c-44e3-8c42-4ad2ed499099.png)

**Comment by scottrblock** [comment]
Hey @glicksman, I just published a new version of the logseq plugin that fixes this. You should be able to update to version `v0.2.7`, which should solve the issue!

**Comment by glicksman** [comment]
Amazing, thanks!!
