### ISSUE TITLE
Feature Request: Logseq fetch captured content automatically (instead of just manaual)

### ISSUE THREAD

**Issue by glicksman** [phonetonote/phonetonote-logseq#11]
Hey, small request:

Today, to fetch the things I've captured on Phonetonote, I need to manual press:
![image](https://user-images.githubusercontent.com/102949603/162244960-8b78fe35-6700-4c14-8326-3a4d41db1b73.png)

Is it possible to have a setting to set an automatic pull (every 30 sec/ 1min/ 2min/ 5min/ 15min/ 60min) to pull things into Logseq? That's how it is in Roam Research, but not in Logseq.

(I constantly forget to manually press it, when processing my inbox)

**Comment by scottrblock** [comment]
hey @glicksman, v0.3.0 now has an option to auto sync (when logseq opens and every 90 seconds afer). update the plugin and you should be good to go. there's some other nice customization options you might be used to from the roam plugin available in logseq now too. you can see them all in the plugin's settings, which will now open in a much more user-friendly modal!
