### ISSUE TITLE
How does one configure this?

### ISSUE THREAD

**Issue by thams** [phonetonote/phonetonote-logseq#5]
Using "open settings" from the LogSeq plugin page opened two text files but unfortunately I closed them and now it doesn't open them again.

**Comment by scottrblock** [comment]
there's not much of the way in configuration yet, but after installing it, you should see a phone with sms icon, that if you click takes you to `phonetonote-logseq` page. on that page you need a `ptn_key` block, and nested underneath that you put your ptn_key. then you click the phone icon again, and it should fetch your notes. i should really get that into the readme 😅

**Comment by thams** [comment]
Ah. Ok, I didn't notice that icon. 

I clicked it, and _briefly_ get
`make a block called ptn_key on this page and put your ptn_key under it` but then the message disappears, just FYI

**Comment by bcohen44** [comment]
I don't see the little phone icon.  I unpacked/loaded the plugin.  Not sure what I am doing wrong
![CleanShot 2021-12-17 at 12 00 45](https://user-images.githubusercontent.com/6190190/146580845-dcfa0a4f-37c5-46f6-8589-1fa53bc36e79.png)

**Comment by scottrblock** [comment]
> Ah. Ok, I didn't notice that icon.
> 
> I clicked it, and _briefly_ get `make a block called ptn_key on this page and put your ptn_key under it` but then the message disappears, just FYI

yea, towards the very top of my dev todo list is making the ui/ux better here, I just used the default logseq error message as a quick mvp

**Comment by scottrblock** [comment]
> I don't see the little phone icon. I unpacked/loaded the plugin. Not sure what I am doing wrong ![CleanShot 2021-12-17 at 12 00 45](https://user-images.githubusercontent.com/6190190/146580845-dcfa0a4f-37c5-46f6-8589-1fa53bc36e79.png)

@bcohen44 can you open the dev console and see if there's any errors there?

i'ts possible you need to manually make the `phonetonote-logseq` page. I thought I was trying to make it if it doesn't exist, but that might not be working/tested against latest logseq release

**Comment by bcohen44** [comment]
ok, following new README directions.  I get this:
```

irbt-9135m:phonetonote-logseq-master bcohen$ yarn build
yarn run v1.22.17
$ parcel build --public-url . --no-source-maps index.html
/bin/sh: parcel: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
irbt-9135m:phonetonote-logseq-master bcohen$ 
```

And the config of _ptn.js
![CleanShot 2021-12-21 at 15 23 29](https://user-images.githubusercontent.com/6190190/146993018-e5908b5d-0b58-4177-951b-e4816914820d.png)
on should look like?

**Comment by scottrblock** [comment]
hey @bcohen44, that's missing a `,` after `false`, which is why `ptn_key` is sqigglied on the next line. in any event, i'd suggest reinstalling from the marketplace so you get the latest version
